name: Update Atlassian Docs

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: feature branch to deploy
        default: test-action
        required: true 

run-name: ${{ inputs.branch }}

jobs:
  update-docs:
    name: Update Atlassian Docs
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # - name: clean install
      #   run: npm ci
      
      - name: publish to confluence
        uses: markdown-confluence/publish-action@main
        with:
          atlassianUserName: ${{ secrets.ATLASSIAN_USERNAME }}
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
