name: Update Atlassian Docs

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: feature branch to deploy
        default: test-action
        required: true 

run-name: ${{ inputs.branch }}

permissions:
      contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  update-docs:
    name: Update Atlassian Docs
    
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v3
      
      - name: publish to confluence
        uses: cupcakearmy/confluence-markdown-sync@v1
        with:
          from: 'device-types.md'
          to: '3755081907'
          cloud: geappliances
          user: ${{ secrets.ATLASSIAN_USERNAME }}
          token: ${{ secrets.ATLASSIAN_API_TOKEN }}
