name: Update Atlassian Docs

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: feature branch to deploy
        required: true 

run-name: ${{ inputs.branch }}

jobs:
  update-docs:
    name: Update Atlassian Docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: publish to confluence
        uses: markdown-confluence/publish-action@v5
        with:
          folderToPublish: docs
          confluenceBaseUrl: https://geappliances.atlassian.net/wiki/spaces/SHSCT
          confluenceParentId: 3755081907
          atlassianUserName: ${{ secrets.ATLASSIAN_USERNAME }}
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
